###############

GPU: [4,5]

VERBOSE: True

MODEL:
  MODE: 'Enhancement'
  SESSION: 'Low-light Image Enhancement(LoL)-LWISP-CutFreq'

# Optimization arguments.
OPTIM:
  BATCH_SIZE: 16
  NUM_EPOCHS: 120
  LR_INITIAL: 2e-4
  #NEPOCH_DECAY: [40]
  #BETA1: 0.9

TRAINING:
  TRAIN_PS: 128
  VAL_PS: 196
  RESUME: False
  ALPHA: 0.05
  BETA: 0.5
  TRAIN_DIR: '../LoL_data' # path to training data
  VAL_DIR: './datasets/lol'     # path to validation data
  SAVE_DIR: './LoL_save'          # path to save models and images
  SAVE_IMAGES: False
  #VAL_AFTER_EVERY: 1
